= info-process-builder
:toc:

== Rationale

As a Clojure developer I use Java's https://docs.oracle.com/javase/8/docs/api/java/lang/ProcessBuilder.html[ProcessBuilder] to spawn scripts and command line applications.
I'd like to better understand how it behaves.

Command line escaping on Windows is currently what confuses me, but other behaviors might be explored in the future.

The command line escaping curiosity is borne from a Babashka script I was writing for rewrite-cljc and discussions continued with @borkdude's https://github.com/babashka/process/issues/2[babashka/process library].
In my rewrite-cljc Babashka script, I wanted to pass the following clj-kondo config on the command line:

[source,Clojure]
----
{:output {:include-files ["^src" "^test" "^script"]}}
----
After a few attempts to make this work on Windows, I gave up and moved the config from the command line to a file.

For Windows developers who have embraced WSL2, maybe all these Windows escaping rules less of a concern?
I am still curious.

== Status

Initial notes, have barely started to understand. May return to study this more someday.

== Command Line Escaping

I find I  am often confused by the command escaping rules when for Java's ProcessBuilder on the Windows platform.
Although it is Windows that has me confused, I'll also explore command escaping rules when invoking bash scripts and native executables on Linux and macOS.

There are likely different/better ways to what I've discovered here.
I'll update this work as I learn more.

=== Method

I've created little executables that echo the args they have received.

Example output of such a script called with args `one` `two` `three`:

[source,shell]
----
argc: 3
arg1: one
arg2: two
arg3: three
----

A variable in the equation is how these args get displayed.
Does the method of display affect the output?
I think, but am not yet entirely confident, that I've got the right incantation to tell `.bat` and `.cmd` files not to interpret on `echo`, but a side effect is that args will be display `"with double quotes"`

For Windows I explore:

- `.ps1` - Powershell
- `.bat` - Batch file
- `.cmd` - Cmd file
- `.exe` - Native exe

Note that batch and cmd script variants are identical and expected to behave the same.
I'm including them both to verify that assumption is true.

For Linux and macOS:

- `.sh` - Bash script
- Native exe


A `ptest.clj` Clojure program launches these scripts with various args and is where I experiment with escaping rules.
It might be more prudent, as I move forward, to make this a unit test.

=== References

Windows command line parsing, it turns out, is complex. Here are some references to work through those complexities:

==== Java Bugs Filed

There have been many Java bugs filed against Windows behavior, here are a couple:

- https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6511002[JDK-6511002 : (process) Document the auto-quoting when creating a Windows process; add winQuote, Oracle Java Bug Database]
- https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6276512[JDK-6276512 : (process) Runtime.exec(cmd[\]) ignores quotes around arguments (win), Oracle Java Bug Database]

The Java team seem have concluded that:

[quote]
____
Unfortunately, the Windows API maps most directly to an interface where
Runtime.exec(String) passes the arg string directly to the OS, but
that method is specified to break up its arguments using StringTokenizer,
which is surprisingly rarely what you want.

It's very hard to make changes in this area, because
- they change the behavior, and so are incompatible
- the current behavior (how to pass strings to the OS) is unspecified, and so
  is spec-compliant.

If there's any way at all that the current behavior can be relied upon,
then we really can't change it.
____

Which I'll paraphrase to: we can't generalize to a gong-show.
I sympathize and empathize with the Java developers who had to contend with this.
But I do wonder if modern Microsoft has stabilized here.

=== Current Java Sources

From OpenJDK source, we have:

- https://github.com/openjdk/jdk/blob/master/src/java.base/windows/classes/java/lang/ProcessImpl.java[Windows version of ProcessImpl.java]
- https://github.com/openjdk/jdk/blob/master/src/java.base/windows/native/libjava/ProcessImpl_md.c[Windows native PrcessImpl_md.c]

==== From Microsoft

- https://docs.microsoft.com/en-us/cpp/cpp/main-function-command-line-args[main function and command-line arguments, Microsoft Docs]

==== Analysis from the Wild

- http://daviddeley.com/autohotkey/parameters/parameters.htm[How Command Line Parameters Are Parsed, by David Deley]
- http://www.windowsinspired.com/understanding-the-command-line-string-and-arguments-received-by-a-windows-program/[A Better Way To Understand Quoting and Escaping of Windows Command Line Arguments, by Windows Inspired]
- http://www.windowsinspired.com/how-a-windows-programs-splits-its-command-line-into-individual-arguments/[How a Windows Program Splits Its Command Line Into Individual Arguments, by Windows Inspired]
- https://stackoverflow.com/a/4095133[Stackoverflow answer, by dbenham]

=== Exploring Windows Escaping

For command line escaping we wonder what is happening with the following players:

- Java
- The Windows shell, if involved
- Windows createProcessW
- Windows OS

That's a lot of wondering.

In the following sections I'll use:

- Command shell - to mean the shell invoked by `cmd.exe`
- PowerShell - to mean the shell invoked by `powershell.exe`

==== Cmd & Bat
Observe the following behavior under the Command shell:

[source,bat]
----
>echo "Ar"g"um"e"n"t" W"it"h Sp"aces""
"Ar"g"um"e"n"t" W"it"h Sp"aces""
----

[source,bat]
----
>exe-test.exe "Ar"g"um"e"n"t" W"it"h Sp"aces""
argc: 1
arg1: Argument With Spaces
----

This can seem baffling to the uninitiated.

==== PowerShell

PowerShell seems less complex.


==== Direct Invocation

TODO...

=== Observations

- On Windows, ProcessBuilder will invoke `.bat.`, `.cmd` and `.exe` files directly, but a Powershell `.ps1` script needs to be explicitly invoked via `powershell` executable.

=== Current Open Questions

- What's with the caret? Some docs say the OS deals with this escape character. True?



- The escape rules for `.bat` and `.cmd` are on the complex side.
I can't say I understand how to properly escape for these targets yet.

- Escaping requirements depend on what, if anything, finally ends up being called by script/exe.

- Does the shell that Java is invoked from have any affect?

- UTF8 in command lines?

== Other areas of interest

- It might also be interesting to explore how ProcessBuilder effectively finds applications under Windows.
For example to launch a native executable you don't need to specify the `.exe` extension.
But for a script the extension is require, if I remember correctly.
