==== How does `a` resolve from cwd?

|===
| | Scenario | Cmd Shell | PowerShell | ProcessBuilder

a|[.nowrap]#`+a+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: []
on-path: []
----
a|[.nowrap]
----
cwd\a.com
cwd
----
a|<not found>
a|[.nowrap]
----
cwd\a.exe
cwd
----

a|[.nowrap]#`+a+`#
a|[.nowrap]
----
cwd:     [bat cmd exe ps1]
workdir: []
on-path: []
----
a|[.nowrap]
----
cwd\a.exe
cwd
----
a|<not found>
a|[.nowrap]
----
cwd\a.exe
cwd
----

a|[.nowrap]#`+a+`#
a|[.nowrap]
----
cwd:     [bat cmd ps1]
workdir: []
on-path: []
----
a|[.nowrap]
----
cwd\a.bat
cwd
----
a|<not found>
a|<not found>

a|[.nowrap]#`+a+`#
a|[.nowrap]
----
cwd:     [cmd ps1]
workdir: []
on-path: []
----
a|[.nowrap]
----
cwd\a.cmd
cwd
----
a|<not found>
a|<not found>

a|[.nowrap]#`+a+`#
a|[.nowrap]
----
cwd:     [ps1]
workdir: []
on-path: []
----
a|<not found>
a|<not found>
a|<not found>
|===

==== How does `a.<ext>` resolve from cwd?

|===
| | Scenario | Cmd Shell | PowerShell | ProcessBuilder

a|[.nowrap]#`+a.ps1+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: []
on-path: []
----
a|<opened notepad with cwd\a.ps1>
a|<not found>
a|<not a valid Win32 application>

a|[.nowrap]#`+a.com+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: []
on-path: []
----
a|[.nowrap]
----
cwd\a.com
cwd
----
a|<not found>
a|[.nowrap]
----
cwd\a.com
cwd
----

a|[.nowrap]#`+a.exe+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: []
on-path: []
----
a|[.nowrap]
----
cwd\a.exe
cwd
----
a|<not found>
a|[.nowrap]
----
cwd\a.exe
cwd
----

a|[.nowrap]#`+a.bat+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: []
on-path: []
----
a|[.nowrap]
----
cwd\a.bat
cwd
----
a|<not found>
a|[.nowrap]
----
cwd\a.bat
cwd
----

a|[.nowrap]#`+a.cmd+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: []
on-path: []
----
a|[.nowrap]
----
cwd\a.cmd
cwd
----
a|<not found>
a|[.nowrap]
----
cwd\a.cmd
cwd
----
|===

==== How does `a.<ext>` resolve from cwd when also on PATH?

|===
| | Scenario | Cmd Shell | PowerShell | ProcessBuilder

a|[.nowrap]#`+a.ps1+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: []
on-path: [bat cmd com exe ps1]
----
a|<opened notepad with cwd\a.ps1>
a|[.nowrap]
----
on-path\a.ps1
cwd
----
a|<not a valid Win32 application>

a|[.nowrap]#`+a.com+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: []
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
cwd\a.com
cwd
----
a|[.nowrap]
----
on-path\a.com
cwd
----
a|[.nowrap]
----
cwd\a.com
cwd
----

a|[.nowrap]#`+a.exe+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: []
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
cwd\a.exe
cwd
----
a|[.nowrap]
----
on-path\a.exe
cwd
----
a|[.nowrap]
----
cwd\a.exe
cwd
----

a|[.nowrap]#`+a.bat+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: []
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
cwd\a.bat
cwd
----
a|[.nowrap]
----
on-path\a.bat
cwd
----
a|[.nowrap]
----
cwd\a.bat
cwd
----

a|[.nowrap]#`+a.cmd+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: []
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
cwd\a.cmd
cwd
----
a|[.nowrap]
----
on-path\a.cmd
cwd
----
a|[.nowrap]
----
cwd\a.cmd
cwd
----

a|[.nowrap]#`+a.ps1+`#
a|[.nowrap]
----
cwd:     []
workdir: []
on-path: [bat cmd com exe ps1]
----
a|<opened notepad with on-path\a.ps1>
a|[.nowrap]
----
on-path\a.ps1
cwd
----
a|<not a valid Win32 application>

a|[.nowrap]#`+a.com+`#
a|[.nowrap]
----
cwd:     []
workdir: []
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
on-path\a.com
cwd
----
a|[.nowrap]
----
on-path\a.com
cwd
----
a|[.nowrap]
----
on-path\a.com
cwd
----

a|[.nowrap]#`+a.exe+`#
a|[.nowrap]
----
cwd:     []
workdir: []
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
on-path\a.exe
cwd
----
a|[.nowrap]
----
on-path\a.exe
cwd
----
a|[.nowrap]
----
on-path\a.exe
cwd
----

a|[.nowrap]#`+a.bat+`#
a|[.nowrap]
----
cwd:     []
workdir: []
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
on-path\a.bat
cwd
----
a|[.nowrap]
----
on-path\a.bat
cwd
----
a|[.nowrap]
----
on-path\a.bat
cwd
----

a|[.nowrap]#`+a.cmd+`#
a|[.nowrap]
----
cwd:     []
workdir: []
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
on-path\a.cmd
cwd
----
a|[.nowrap]
----
on-path\a.cmd
cwd
----
a|[.nowrap]
----
on-path\a.cmd
cwd
----
|===

==== How does `a` resolve from cwd when also on `PATH`?

|===
| | Scenario | Cmd Shell | PowerShell | ProcessBuilder

a|[.nowrap]#`+a+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: []
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
cwd\a.com
cwd
----
a|[.nowrap]
----
on-path\a.ps1
cwd
----
a|[.nowrap]
----
cwd\a.exe
cwd
----

a|[.nowrap]#`+a+`#
a|[.nowrap]
----
cwd:     [bat cmd exe ps1]
workdir: []
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
cwd\a.exe
cwd
----
a|[.nowrap]
----
on-path\a.ps1
cwd
----
a|[.nowrap]
----
cwd\a.exe
cwd
----

a|[.nowrap]#`+a+`#
a|[.nowrap]
----
cwd:     [bat cmd ps1]
workdir: []
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
cwd\a.bat
cwd
----
a|[.nowrap]
----
on-path\a.ps1
cwd
----
a|[.nowrap]
----
on-path\a.exe
cwd
----

a|[.nowrap]#`+a+`#
a|[.nowrap]
----
cwd:     [cmd ps1]
workdir: []
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
cwd\a.cmd
cwd
----
a|[.nowrap]
----
on-path\a.ps1
cwd
----
a|[.nowrap]
----
on-path\a.exe
cwd
----

a|[.nowrap]#`+a+`#
a|[.nowrap]
----
cwd:     [ps1]
workdir: []
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
on-path\a.com
cwd
----
a|[.nowrap]
----
on-path\a.ps1
cwd
----
a|[.nowrap]
----
on-path\a.exe
cwd
----

a|[.nowrap]#`+a+`#
a|[.nowrap]
----
cwd:     [ps1]
workdir: []
on-path: [bat cmd com exe]
----
a|[.nowrap]
----
on-path\a.com
cwd
----
a|[.nowrap]
----
on-path\a.com
cwd
----
a|[.nowrap]
----
on-path\a.exe
cwd
----

a|[.nowrap]#`+a+`#
a|[.nowrap]
----
cwd:     [ps1]
workdir: []
on-path: [bat cmd exe]
----
a|[.nowrap]
----
on-path\a.exe
cwd
----
a|[.nowrap]
----
on-path\a.exe
cwd
----
a|[.nowrap]
----
on-path\a.exe
cwd
----

a|[.nowrap]#`+a+`#
a|[.nowrap]
----
cwd:     [ps1]
workdir: []
on-path: [bat cmd]
----
a|[.nowrap]
----
on-path\a.bat
cwd
----
a|[.nowrap]
----
on-path\a.bat
cwd
----
a|<not found>

a|[.nowrap]#`+a+`#
a|[.nowrap]
----
cwd:     [ps1]
workdir: []
on-path: [cmd]
----
a|[.nowrap]
----
on-path\a.cmd
cwd
----
a|[.nowrap]
----
on-path\a.cmd
cwd
----
a|<not found>

a|[.nowrap]#`+a+`#
a|[.nowrap]
----
cwd:     [ps1]
workdir: []
on-path: []
----
a|<not found>
a|<not found>
a|<not found>
|===

==== How does `.\a` resolve from cwd?

|===
| | Scenario | Cmd Shell | PowerShell | ProcessBuilder

a|[.nowrap]#`+.\a+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: []
on-path: []
----
a|[.nowrap]
----
cwd\a.com
cwd
----
a|[.nowrap]
----
cwd\a.ps1
cwd
----
a|[.nowrap]
----
cwd\a.exe
cwd
----

a|[.nowrap]#`+.\a+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe]
workdir: []
on-path: []
----
a|[.nowrap]
----
cwd\a.com
cwd
----
a|[.nowrap]
----
cwd\a.com
cwd
----
a|[.nowrap]
----
cwd\a.exe
cwd
----

a|[.nowrap]#`+.\a+`#
a|[.nowrap]
----
cwd:     [bat cmd exe]
workdir: []
on-path: []
----
a|[.nowrap]
----
cwd\a.exe
cwd
----
a|[.nowrap]
----
cwd\a.exe
cwd
----
a|[.nowrap]
----
cwd\a.exe
cwd
----

a|[.nowrap]#`+.\a+`#
a|[.nowrap]
----
cwd:     [bat cmd]
workdir: []
on-path: []
----
a|[.nowrap]
----
cwd\a.bat
cwd
----
a|[.nowrap]
----
cwd\a.bat
cwd
----
a|<not found>

a|[.nowrap]#`+.\a+`#
a|[.nowrap]
----
cwd:     [cmd]
workdir: []
on-path: []
----
a|[.nowrap]
----
cwd\a.cmd
cwd
----
a|[.nowrap]
----
cwd\a.cmd
cwd
----
a|<not found>
|===

==== How does `.\a.<ext>` resolve from cwd?

|===
| | Scenario | Cmd Shell | PowerShell | ProcessBuilder

a|[.nowrap]#`+.\a.ps1+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: []
on-path: []
----
a|<opened notepad with cwd\a.ps1>
a|[.nowrap]
----
cwd\a.ps1
cwd
----
a|<not a valid Win32 application>

a|[.nowrap]#`+.\a.com+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: []
on-path: []
----
a|[.nowrap]
----
cwd\a.com
cwd
----
a|[.nowrap]
----
cwd\a.com
cwd
----
a|[.nowrap]
----
cwd\a.com
cwd
----

a|[.nowrap]#`+.\a.exe+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: []
on-path: []
----
a|[.nowrap]
----
cwd\a.exe
cwd
----
a|[.nowrap]
----
cwd\a.exe
cwd
----
a|[.nowrap]
----
cwd\a.exe
cwd
----

a|[.nowrap]#`+.\a.bat+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: []
on-path: []
----
a|[.nowrap]
----
cwd\a.bat
cwd
----
a|[.nowrap]
----
cwd\a.bat
cwd
----
a|[.nowrap]
----
cwd\a.bat
cwd
----

a|[.nowrap]#`+.\a.cmd+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: []
on-path: []
----
a|[.nowrap]
----
cwd\a.cmd
cwd
----
a|[.nowrap]
----
cwd\a.cmd
cwd
----
a|[.nowrap]
----
cwd\a.cmd
cwd
----
|===

==== We expect absolute path of `a.<ext>` to work fine, do they?

|===
| | Scenario | Cmd Shell | PowerShell | ProcessBuilder

a|[.nowrap]#`+Z:\...\cwd\a.ps1+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|<opened notepad with cwd\a.ps1>
a|[.nowrap]
----
cwd\a.ps1
cwd
----
a|<not a valid Win32 application>

a|[.nowrap]#`+Z:\...\cwd\a.com+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
cwd\a.com
cwd
----
a|[.nowrap]
----
cwd\a.com
cwd
----
a|[.nowrap]
----
cwd\a.com
cwd
----

a|[.nowrap]#`+Z:\...\cwd\a.exe+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
cwd\a.exe
cwd
----
a|[.nowrap]
----
cwd\a.exe
cwd
----
a|[.nowrap]
----
cwd\a.exe
cwd
----

a|[.nowrap]#`+Z:\...\cwd\a.bat+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
cwd\a.bat
cwd
----
a|[.nowrap]
----
cwd\a.bat
cwd
----
a|[.nowrap]
----
cwd\a.bat
cwd
----

a|[.nowrap]#`+Z:\...\cwd\a.cmd+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
cwd\a.cmd
cwd
----
a|[.nowrap]
----
cwd\a.cmd
cwd
----
a|[.nowrap]
----
cwd\a.cmd
cwd
----

a|[.nowrap]#`+Z:\...\workdir\a.ps1+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|<opened notepad with workdir\a.ps1>
a|[.nowrap]
----
workdir\a.ps1
cwd
----
a|<not a valid Win32 application>

a|[.nowrap]#`+Z:\...\workdir\a.com+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
workdir\a.com
cwd
----
a|[.nowrap]
----
workdir\a.com
cwd
----
a|[.nowrap]
----
workdir\a.com
cwd
----

a|[.nowrap]#`+Z:\...\workdir\a.exe+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
workdir\a.exe
cwd
----
a|[.nowrap]
----
workdir\a.exe
cwd
----
a|[.nowrap]
----
workdir\a.exe
cwd
----

a|[.nowrap]#`+Z:\...\workdir\a.bat+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
workdir\a.bat
cwd
----
a|[.nowrap]
----
workdir\a.bat
cwd
----
a|[.nowrap]
----
workdir\a.bat
cwd
----

a|[.nowrap]#`+Z:\...\workdir\a.cmd+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
workdir\a.cmd
cwd
----
a|[.nowrap]
----
workdir\a.cmd
cwd
----
a|[.nowrap]
----
workdir\a.cmd
cwd
----

a|[.nowrap]#`+Z:\...\on-path\a.ps1+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|<opened notepad with on-path\a.ps1>
a|[.nowrap]
----
on-path\a.ps1
cwd
----
a|<not a valid Win32 application>

a|[.nowrap]#`+Z:\...\on-path\a.com+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
on-path\a.com
cwd
----
a|[.nowrap]
----
on-path\a.com
cwd
----
a|[.nowrap]
----
on-path\a.com
cwd
----

a|[.nowrap]#`+Z:\...\on-path\a.exe+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
on-path\a.exe
cwd
----
a|[.nowrap]
----
on-path\a.exe
cwd
----
a|[.nowrap]
----
on-path\a.exe
cwd
----

a|[.nowrap]#`+Z:\...\on-path\a.bat+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
on-path\a.bat
cwd
----
a|[.nowrap]
----
on-path\a.bat
cwd
----
a|[.nowrap]
----
on-path\a.bat
cwd
----

a|[.nowrap]#`+Z:\...\on-path\a.cmd+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
on-path\a.cmd
cwd
----
a|[.nowrap]
----
on-path\a.cmd
cwd
----
a|[.nowrap]
----
on-path\a.cmd
cwd
----
|===

==== How does `a` with workdir resolve from cwd, workdir, `PATH`?

|===
| | Scenario | ProcessBuilder

a|[.nowrap]#`+a+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
cwd\a.exe
workdir
----

a|[.nowrap]#`+a+`#
a|[.nowrap]
----
cwd:     [bat cmd com ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
on-path\a.exe
workdir
----

a|[.nowrap]#`+a+`#
a|[.nowrap]
----
cwd:     [bat cmd com ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com ps1]
----
a|<not found>
|===

==== How does `a.<ext>` with workdir resolve from cwd, workdir, `PATH``?

|===
| | Scenario | ProcessBuilder

a|[.nowrap]#`+a.ps1+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|<not a valid Win32 application>

a|[.nowrap]#`+a.ps1+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|<not a valid Win32 application>

a|[.nowrap]#`+a.com+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
cwd\a.com
workdir
----

a|[.nowrap]#`+a.com+`#
a|[.nowrap]
----
cwd:     [bat cmd exe]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
on-path\a.com
workdir
----

a|[.nowrap]#`+a.exe+`#
a|[.nowrap]
----
cwd:     [bat cmd exe]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
cwd\a.exe
workdir
----

a|[.nowrap]#`+a.exe+`#
a|[.nowrap]
----
cwd:     [bat cmd]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
on-path\a.exe
workdir
----

a|[.nowrap]#`+a.bat+`#
a|[.nowrap]
----
cwd:     [bat cmd]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
workdir\a.bat
workdir
----

a|[.nowrap]#`+a.bat+`#
a|[.nowrap]
----
cwd:     [bat cmd]
workdir: [cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
on-path\a.bat
workdir
----

a|[.nowrap]#`+a.cmd+`#
a|[.nowrap]
----
cwd:     [cmd]
workdir: [cmd]
on-path: [cmd]
----
a|[.nowrap]
----
workdir\a.cmd
workdir
----

a|[.nowrap]#`+a.cmd+`#
a|[.nowrap]
----
cwd:     [cmd]
workdir: []
on-path: [cmd]
----
a|[.nowrap]
----
on-path\a.cmd
workdir
----
|===

==== How does `.\a` with workdir resolve from cwd, workdir?

|===
| | Scenario | ProcessBuilder

a|[.nowrap]#`+.\a+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
cwd\a.exe
workdir
----

a|[.nowrap]#`+.\a+`#
a|[.nowrap]
----
cwd:     [bat cmd com ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|<not found>
|===

==== How does `.\a.<ext>` with workdir resolve from cwd, workdir?

|===
| | Scenario | ProcessBuilder

a|[.nowrap]#`+.\a.ps1+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|<not a valid Win32 application>

a|[.nowrap]#`+.\a.com+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
cwd\a.com
workdir
----

a|[.nowrap]#`+.\a.exe+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
cwd\a.exe
workdir
----

a|[.nowrap]#`+.\a.bat+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
workdir\a.bat
workdir
----

a|[.nowrap]#`+.\a.bat+`#
a|[.nowrap]
----
cwd:     [cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|<not found>

a|[.nowrap]#`+.\a.cmd+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
workdir\a.cmd
workdir
----

a|[.nowrap]#`+.\a.cmd+`#
a|[.nowrap]
----
cwd:     [bat com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|<not found>
|===

==== We expect absolute path of `a.<ext>` with workdir to work fine, do they?

|===
| | Scenario | ProcessBuilder

a|[.nowrap]#`+Z:\...\cwd\a.ps1+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|<not a valid Win32 application>

a|[.nowrap]#`+Z:\...\cwd\a.com+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
cwd\a.com
workdir
----

a|[.nowrap]#`+Z:\...\cwd\a.exe+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
cwd\a.exe
workdir
----

a|[.nowrap]#`+Z:\...\cwd\a.bat+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
cwd\a.bat
workdir
----

a|[.nowrap]#`+Z:\...\cwd\a.cmd+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
cwd\a.cmd
workdir
----

a|[.nowrap]#`+Z:\...\workdir\a.ps1+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|<not a valid Win32 application>

a|[.nowrap]#`+Z:\...\workdir\a.com+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
workdir\a.com
workdir
----

a|[.nowrap]#`+Z:\...\workdir\a.exe+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
workdir\a.exe
workdir
----

a|[.nowrap]#`+Z:\...\workdir\a.bat+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
workdir\a.bat
workdir
----

a|[.nowrap]#`+Z:\...\workdir\a.cmd+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
workdir\a.cmd
workdir
----

a|[.nowrap]#`+Z:\...\on-path\a.ps1+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|<not a valid Win32 application>

a|[.nowrap]#`+Z:\...\on-path\a.com+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
on-path\a.com
workdir
----

a|[.nowrap]#`+Z:\...\on-path\a.exe+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
on-path\a.exe
workdir
----

a|[.nowrap]#`+Z:\...\on-path\a.bat+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
on-path\a.bat
workdir
----

a|[.nowrap]#`+Z:\...\on-path\a.cmd+`#
a|[.nowrap]
----
cwd:     [bat cmd com exe ps1]
workdir: [bat cmd com exe ps1]
on-path: [bat cmd com exe ps1]
----
a|[.nowrap]
----
on-path\a.cmd
workdir
----
|===
